# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: sphinx/conf.py
  fail_on_warning: true

# Build documentation with MkDocs
#mkdocs:
#  configuration: mkdocs.yml

# Optionally build your docs in additional formats such as PDF and ePub
formats: all

build:
  os: ubuntu-24.04
  tools:
    python: "mambaforge-22.9"
  jobs:
    pre_build:
          - curl -fL https://repo.maven.apache.org/maven2/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar -o /tmp/test.jar
      - which java
      - readlink -f "$(which java)"
      - java -version 2>&1
      - which mvn
      - mvn -version

# Optionally set the version of Python and requirements required to build your docs
python:
  install:
    - requirements: requirements.txt

conda:
  environment: environment.yml
